#!/bin/bash

# sysinfo_page - A script to copy latex templates from one directory to another

#### Constants
DIR="/home/domnik/Documents/latex/templates/"

#### Functions

if [ "$1" != "" ]; then
		if [ "$2" != "" ]; then
				if [ -f "$(pwd)/$2.tex" ]; then
					echo "File already exists"
				else
					cp $DIR$1.tex $(pwd)/$2.tex
					vim $2.tex
				fi
		else
				if [ -f "$(pwd)/$2.tex" ]; then
					echo "File already exists"
				else
					cp $DIR$1.tex $(pwd)/$1.tex
					vim $1.tex
				fi
		fi
else
		echo "usage: template <name>"
fi
