#!/bin/python

import os
import pathlib
import argparse
import shutil

home = pathlib.Path.home()
cwd = os.getcwd()
templates = os.listdir(f"{home}/Templates/latex")

parser = argparse.ArgumentParser(description='Copy and rename latex templates')
parser.add_argument('template', type=str, help='Name of a template', nargs=1, choices=templates)
parser.add_argument('name', type=str, help='New file name', nargs='?')

args = vars(parser.parse_args())

template = args["template"][0]

if args["name"] == None:
    name = template
else:
    name = args["name"]

src = f"{home}/Templates/latex/{template}"
dst = f"{cwd}/{name}"

try:
    shutil.copytree(src, dst, dirs_exist_ok=False)
    shutil.move(f"{dst}/{template}.tex", f"{dst}/{name}.tex")
except FileExistsError:
    print(f"File {name} already exists")


